# 1. 声明 K8s 内部虚拟服务
apiVersion: v1
kind: Service
metadata:
  name: dameng-external-service
  namespace: edge-apps
spec:
  ports:
    - name: dmsql
      port: 5236
      targetPort: 5236
---
# 2. 将流量精准引流至 openEuler 的实际宿主机 IP
apiVersion: v1
kind: Endpoints
metadata:
  name: dameng-external-service
  namespace: edge-apps
subsets:
  - addresses:
      - ip: 172.29.199.115       # openEuler / 外部达梦所在的主机 IP
    ports:
      - name: dmsql
        port: 5236
